# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 736)
        MainWindow.setStyleSheet("background-color: #000000")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 280))
        self.frame.setStyleSheet("background-color: #FF932F")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.name_app = QtWidgets.QLabel(self.frame)
        self.name_app.setGeometry(QtCore.QRect(90, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.name_app.setFont(font)
        self.name_app.setObjectName("name_app")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 80, 191, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/currency-exchange_logo200.png"))
        self.label.setObjectName("label")
        self.inputCurrency = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCurrency.setGeometry(QtCore.QRect(50, 310, 380, 60))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputCurrency.setFont(font)
        self.inputCurrency.setStyleSheet("background-color: #8022222e;\n"
"border: 2px solid #FF932F;\n"
"border-radius: 30;\n"
"color: white;")
        self.inputCurrency.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCurrency.setObjectName("inputCurrency")
        self.inputAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAmount.setGeometry(QtCore.QRect(50, 390, 380, 60))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputAmount.setFont(font)
        self.inputAmount.setStyleSheet("background-color: #8022222e;\n"
"border: 2px solid #FF932F;\n"
"border-radius: 30;\n"
"color: white;")
        self.inputAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.inputAmount.setObjectName("inputAmount")
        self.outputCurrency = QtWidgets.QLineEdit(self.centralwidget)
        self.outputCurrency.setGeometry(QtCore.QRect(50, 470, 380, 60))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputCurrency.setFont(font)
        self.outputCurrency.setStyleSheet("background-color: #8022222e;\n"
"border: 2px solid #FF932F;\n"
"border-radius: 30;\n"
"color: white;")
        self.outputCurrency.setAlignment(QtCore.Qt.AlignCenter)
        self.outputCurrency.setObjectName("outputCurrency")
        self.outputAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.outputAmount.setGeometry(QtCore.QRect(50, 550, 380, 60))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputAmount.setFont(font)
        self.outputAmount.setStyleSheet("background-color: #8022222e;\n"
"border: 2px solid #FF932F;\n"
"border-radius: 30;\n"
"color: white;")
        self.outputAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.outputAmount.setObjectName("outputAmount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 640, 380, 60))
        font = QtGui.QFont()
        font.setFamily("FreeSerif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:  #22222e;\n"
"    border: 2px solid #FF932F;\n"
"    border-radius: 30;\n"
"    color: white\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #FF932F\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертер валют"))
        self.name_app.setText(_translate("MainWindow", "КОНВЕРТЕР ВАЛЮТ"))
        self.inputCurrency.setToolTip(_translate("MainWindow", "Введите исходную валюту"))
        self.inputCurrency.setPlaceholderText(_translate("MainWindow", "Валюта:"))
        self.inputAmount.setToolTip(_translate("MainWindow", "Введите количество"))
        self.inputAmount.setPlaceholderText(_translate("MainWindow", "Введите количество:"))
        self.outputCurrency.setToolTip(_translate("MainWindow", "В какой валюте"))
        self.outputCurrency.setPlaceholderText(_translate("MainWindow", "В какой валюте:"))
        self.outputAmount.setToolTip(_translate("MainWindow", "Ваш результат"))
        self.outputAmount.setPlaceholderText(_translate("MainWindow", "Результат:"))
        self.pushButton.setToolTip(_translate("MainWindow", "Конвертировать"))
        self.pushButton.setText(_translate("MainWindow", "Конвертировать"))
